In [1]:
import os
import numpy as np
import pandas as pd
from osgeo import gdal
import matplotlib.pyplot as plt
# netCDF4 needs to be installed in your environment for this to work
import xarray as xr
import rioxarray as rio
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import seaborn as sns
import geopandas as gpd
import earthpy as et
# Plotting options
sns.set(font_scale=1.3)
sns.set_style("white")

To obtain, district and mandal level data, We have used **rasterToVector.py** script

In [3]:
district_path = "convert\\districts"
mandal_path = "convert\\mandals"

In [4]:
district_dataset = [ds for ds in os.listdir(district_path) if ds[-8:] == '.geojson']
mandal_dataset = [ds for ds in os.listdir(mandal_path) if ds[-8:] == '.geojson']

In [5]:
len(district_dataset)

1

In [6]:
mandal = gpd.read_file(mandal_path+"/"+mandal_dataset[0])
district =  gpd.read_file(district_path + "/" + district_dataset[0])

In [7]:
ssm = []
for i in range (0, len(mandal)):
    ssm.append(mandal["zonalstat"][i]['mean'])

In [8]:
mandal["ssm"] = ssm

In [9]:
mandal = mandal[["Mandal_Nam","geometry","ssm"]]

In [10]:
ssm = []
for i in range (0, len(district)):
    ssm.append(district["zonalstat"][i]['mean'])

In [11]:
district["ssm"] = ssm

In [12]:
district

,Area,Dist_Name,uid,zonalstat,geometry,ssm
0,6974.142517,Bhadradri Kothagudem,TDID1,"{'min': -0.015397, 'max': 0.040498, 'mean': 0....","POLYGON ((80.91930 17.21950, 80.93816 17.21971...",0.008722
1,2853.088839,Jagtial,TDID2,"{'min': -0.006445, 'max': 0.042049, 'mean': 0....","POLYGON ((79.29767 18.81833, 79.27566 18.82538...",0.024813
2,2112.708002,Jangoan,TDID3,"{'min': -0.015052, 'max': 0.019876, 'mean': 0....","POLYGON ((79.23083 17.99250, 79.19182 17.99887...",0.008375
3,4189.022904,Mulugu,TDID4,"{'min': -0.003973, 'max': 0.020436, 'mean': 0....","POLYGON ((79.84389 18.15964, 79.85469 18.14713...",0.007191
4,3701.834985,Kamareddy,TDID5,"{'min': -0.029356, 'max': 0.013538, 'mean': -0...","POLYGON ((78.52433 18.46778, 78.51680 18.46579...",-0.012010
5,2127.790076,Karimnagar,TDID6,"{'min': 0.007063, 'max': 0.024226, 'mean': 0.0...","POLYGON ((79.12410 18.66557, 79.11729 18.66475...",0.014541
6,4491.247740,Khammam,TDID7,"{'min': -0.014015, 'max': 0.040425, 'mean': 0....","POLYGON ((80.91930 17.21950, 80.89326 17.22221...",0.021372
7,3551.035197,Mahabubabad,TDID8,"{'min': -0.001057, 'max': 0.046656, 'mean': 0....","POLYGON ((79.56249 17.61965, 79.56047 17.60609...",0.019821
8,3909.400107,Mancherial,TDID9,"{'min': 0.00267, 'max': 0.036592, 'mean': 0.01...","POLYGON ((79.93091 19.15612, 79.92258 19.16502...",0.015982
9,2771.683489,Medak,TDID10,"{'min': 0.005214, 'max': 0.03101, 'mean': 0.01...","POLYGON ((78.56878 18.18295, 78.56602 18.17606...",0.017486
10,6399.069250,Nagarkurnool,TDID11,"{'min': -0.057937, 'max': 0.070824, 'mean': 0....","POLYGON ((78.79234 16.77508, 78.78942 16.77236...",0.007978
11,7218.261624,Nalgonda,TDID12,"{'min': -0.010577, 'max': 0.045526, 'mean': 0....","POLYGON ((79.45808 17.34321, 79.43876 17.34583...",0.017989
12,3729.128537,Nirmal,TDID13,"{'min': 0.011571, 'max': 0.042725, 'mean': 0.0...","POLYGON ((78.19343 19.31739, 78.19283 19.31133...",0.028494
13,4168.328627,Nizamabad,TDID14,"{'min': -0.032861, 'max': 0.043864, 'mean': -0...","POLYGON ((78.53865 18.94646, 78.52825 18.94876...",-0.002833
14,2195.386919,Peddapalli,TDID15,"{'min': 0.005474, 'max': 0.024358, 'mean': 0.0...","POLYGON ((79.81232 18.71031, 79.77836 18.69352...",0.013965
15,1897.965133,Rajanna Sircilla,TDID16,"{'min': -0.024907, 'max': 0.025372, 'mean': 0....","POLYGON ((78.63439 18.68997, 78.62140 18.69041...",0.002276
16,4460.372617,Sangareddy,TDID17,"{'min': -0.025374, 'max': 0.03058, 'mean': 0.0...","POLYGON ((77.89728 18.09283, 77.90558 18.10270...",0.000205
17,3637.171244,Siddipet,TDID18,"{'min': 0.000659, 'max': 0.02498, 'mean': 0.01...","POLYGON ((79.30336 18.13246, 79.28805 18.13941...",0.013137
18,3618.963690,Vikarabad,TDID19,"{'min': -0.025694, 'max': -0.004194, 'mean': -...","POLYGON ((77.68707 17.51164, 77.69243 17.50025...",-0.017497
19,2174.667812,Wanaparthy,TDID20,"{'min': -0.031983, 'max': 0.072648, 'mean': 0....","POLYGON ((78.12572 16.59273, 78.11601 16.59768...",0.001252
20,2139.979523,Warangal Rural,TDID21,"{'min': -0.003567, 'max': 0.018215, 'mean': 0....","POLYGON ((79.84389 18.15964, 79.83835 18.15761...",0.009413
21,1294.451557,Warangal Urban,TDID22,"{'min': -0.002238, 'max': 0.029019, 'mean': 0....","POLYGON ((79.58152 18.25619, 79.56271 18.26249...",0.011692
22,3422.720510,Yadadri Bhuvanagiri,TDID23,"{'min': -0.017046, 'max': 0.030994, 'mean': 0....","POLYGON ((79.37870 17.51133, 79.35930 17.52151...",0.012208
23,2380.127435,Narayanpet,TDID24,"{'min': -0.022387, 'max': 0.021266, 'mean': 0....","POLYGON ((77.74330 16.42026, 77.74017 16.42476...",0.003395
24,2574.212440,Jogulamba Gadwal,TDID25,"{'min': -0.011224, 'max': 0.034894, 'mean': 0....","POLYGON ((78.25116 15.97345, 78.24610 15.96161...",0.006630
25,4997.535418,Rangareddy,TDID26,"{'min': -0.043558, 'max': -0.001072, 'mean': -...","POLYGON ((78.40498 17.45017, 78.39164 17.45997...",-0.019493
26,3584.217756,Suryapet,TDID27,"{'min': -0.008576, 'max': 0.036639, 'mean': 0....","POLYGON ((79.80396 17.32162, 79.79254 17.32529...",0.017952
27,1088.524810,Medchal Malkajgiri,TDID28,"{'min': -0.027609, 'max': -0.008481, 'mean': -...","POLYGON ((78.49290 17.69457, 78.46939 17.69209...",-0.012951
28,3980.341589,Adilabad,TDID29,"{'min': 0.006422, 'max': 0.034031, 'mean': 0.0...","POLYGON ((78.94061 19.55204, 78.93819 19.56240...",0.016422
29,182.638047,Hyderabad,TDID30,"{'min': -0.027609, 'max': -0.027609, 'mean': -...","POLYGON ((78.51558 17.37731, 78.51622 17.38332...",-0.027609
30,4495.317152,Kumurambheem Asifabad,TDID31,"{'min': 0.004185, 'max': 0.021489, 'mean': 0.0...","POLYGON ((79.93091 19.15612, 79.94481 19.16827...",0.010060
31,2946.007350,Jayashankar Bhupalpally,TDID32,"{'min': 0.003393, 'max': 0.019785, 'mean': 0.0...","POLYGON ((80.34460 18.59678, 80.33440 18.61359...",0.011076
32,2749.622147,Mahabubnagar,TDID33,"{'min': -0.031989, 'max': -0.013489, 'mean': -...","POLYGON ((78.34856 16.78566, 78.33204 16.79519...",-0.020810

In [13]:
district = district[["Dist_Name","geometry","ssm"]]

In [14]:
mandal

,Mandal_Nam,geometry,ssm
0,Abdullapurmet,"POLYGON ((78.58558 17.34675, 78.60189 17.34188...",-0.030773
1,Achampet,"POLYGON ((79.06269 16.44607, 79.04739 16.45883...",-0.000308
2,Adavidevulapally,"POLYGON ((79.52430 16.72522, 79.48673 16.71371...",0.045526
3,Addagudur,"POLYGON ((79.36517 17.48429, 79.34519 17.46905...",-0.008145
4,Addakal,"POLYGON ((78.00552 16.56734, 78.00110 16.57589...",-0.016775
...,...,...,...
587,Mosra,"POLYGON ((77.93404 18.59345, 77.93417 18.59046...",-0.019526
588,Chandur,"POLYGON ((78.04060 18.49653, 78.03331 18.50814...",-0.015693
589,Chowtakur,"POLYGON ((78.06920 17.67324, 78.07788 17.65484...",0.004975
590,Masaipet,"POLYGON ((78.53362 17.90568, 78.52602 17.91299...",0.014842
591,Dhoolumitta,"POLYGON ((79.12089 17.94057, 79.12931 17.94707...",0.016734

In [15]:
district

,Dist_Name,geometry,ssm
0,Bhadradri Kothagudem,"POLYGON ((80.91930 17.21950, 80.93816 17.21971...",0.008722
1,Jagtial,"POLYGON ((79.29767 18.81833, 79.27566 18.82538...",0.024813
2,Jangoan,"POLYGON ((79.23083 17.99250, 79.19182 17.99887...",0.008375
3,Mulugu,"POLYGON ((79.84389 18.15964, 79.85469 18.14713...",0.007191
4,Kamareddy,"POLYGON ((78.52433 18.46778, 78.51680 18.46579...",-0.012010
5,Karimnagar,"POLYGON ((79.12410 18.66557, 79.11729 18.66475...",0.014541
6,Khammam,"POLYGON ((80.91930 17.21950, 80.89326 17.22221...",0.021372
7,Mahabubabad,"POLYGON ((79.56249 17.61965, 79.56047 17.60609...",0.019821
8,Mancherial,"POLYGON ((79.93091 19.15612, 79.92258 19.16502...",0.015982
9,Medak,"POLYGON ((78.56878 18.18295, 78.56602 18.17606...",0.017486
10,Nagarkurnool,"POLYGON ((78.79234 16.77508, 78.78942 16.77236...",0.007978
11,Nalgonda,"POLYGON ((79.45808 17.34321, 79.43876 17.34583...",0.017989
12,Nirmal,"POLYGON ((78.19343 19.31739, 78.19283 19.31133...",0.028494
13,Nizamabad,"POLYGON ((78.53865 18.94646, 78.52825 18.94876...",-0.002833
14,Peddapalli,"POLYGON ((79.81232 18.71031, 79.77836 18.69352...",0.013965
15,Rajanna Sircilla,"POLYGON ((78.63439 18.68997, 78.62140 18.69041...",0.002276
16,Sangareddy,"POLYGON ((77.89728 18.09283, 77.90558 18.10270...",0.000205
17,Siddipet,"POLYGON ((79.30336 18.13246, 79.28805 18.13941...",0.013137
18,Vikarabad,"POLYGON ((77.68707 17.51164, 77.69243 17.50025...",-0.017497
19,Wanaparthy,"POLYGON ((78.12572 16.59273, 78.11601 16.59768...",0.001252
20,Warangal Rural,"POLYGON ((79.84389 18.15964, 79.83835 18.15761...",0.009413
21,Warangal Urban,"POLYGON ((79.58152 18.25619, 79.56271 18.26249...",0.011692
22,Yadadri Bhuvanagiri,"POLYGON ((79.37870 17.51133, 79.35930 17.52151...",0.012208
23,Narayanpet,"POLYGON ((77.74330 16.42026, 77.74017 16.42476...",0.003395
24,Jogulamba Gadwal,"POLYGON ((78.25116 15.97345, 78.24610 15.96161...",0.006630
25,Rangareddy,"POLYGON ((78.40498 17.45017, 78.39164 17.45997...",-0.019493
26,Suryapet,"POLYGON ((79.80396 17.32162, 79.79254 17.32529...",0.017952
27,Medchal Malkajgiri,"POLYGON ((78.49290 17.69457, 78.46939 17.69209...",-0.012951
28,Adilabad,"POLYGON ((78.94061 19.55204, 78.93819 19.56240...",0.016422
29,Hyderabad,"POLYGON ((78.51558 17.37731, 78.51622 17.38332...",-0.027609
30,Kumurambheem Asifabad,"POLYGON ((79.93091 19.15612, 79.94481 19.16827...",0.010060
31,Jayashankar Bhupalpally,"POLYGON ((80.34460 18.59678, 80.33440 18.61359...",0.011076
32,Mahabubnagar,"POLYGON ((78.34856 16.78566, 78.33204 16.79519...",-0.020810

In [16]:
mandal.to_file("TelanganaSSMMandal.geojson", driver='GeoJSON')
district.to_file("TelanganaSSMDistrict.geojson", driver='GeoJSON')